name: DevSecOps Security Pipeline

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          skip_check: CKV_AWS_135